language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t docker-training -f Dockerfile.dev .

script:
 - docker run -e CI=true docker-training npm run test -- --coverage
